### ISSUE TITLE
Guitarix: Error-Messages due to missing gx_colwah.lv2 files

### ISSUE THREAD

**Issue by OE4AMW** [schnitzeltony/meta-musicians#12]
I tried to build poky with guitarix 0.39.0 (using https://github.com/schnitzeltony/meta-musicians/blob/master/recipes-musicians/guitarix/guitarix.bb ) for a raspberry pi. The compilation succeeded, but when starting, guitarix reports following errors:

error: failed to open file /usr/lib/lv2/gx_colwah.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/gx_colwah.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/gx_colwah.lv2/manifest.ttl

**Comment by schnitzeltony** [comment]
Yes similar here: In qtractor this plugin is grayed. Unfortunately I am no expert at proper contents of turtle files @brummer10: Have attached the ttl.
[gx_colwah.ttl.txt](https://github.com/schnitzeltony/meta-musicians/files/4763742/gx_colwah.ttl.txt)
Is there something missing this plugin requires (e.g. MOD as mentioned in turtle title)?

**Comment by brummer10** [comment]
I'm afraid, it's a upstream bug. It's fixed within our latest release. 
Here is a patch to fix 0.39.0 in case you wouldn't update now to 0.40.0.
https://salsa.debian.org/multimedia-team/guitarix/-/blob/master/debian/patches/1000-wah_colwah_fix.patch

**Comment by schnitzeltony** [comment]
Thanks a lot. Will first try the patch and then upgrade to 0.40.0. Did start the upgrade already but there were issues - so I might ask again then.

**Comment by schnitzeltony** [comment]
@brummer10:

The referenced patch does not apply cleanly on 0.39.0 so I decided to upgrade to 0.40.0 now - it is on my TODO since 0.40.0 was announced - but...

On all sources (tarball / your repo at https://github.com/brummer10/guitarix) build fails with:

> | Waf: Leaving directory `/home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/guitarix/0.40.0+gitAUTOINC+9e6dbe30cb-r0/build'
> | Build failed
> | Traceback (most recent call last):
> |   File "/home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/guitarix/0.40.0+gitAUTOINC+9e6dbe30cb-r0/git/trunk/.waf3-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Runner.py", line 255, in task_status
> |     return tsk.runnable_status()
> |   File "/home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/guitarix/0.40.0+gitAUTOINC+9e6dbe30cb-r0/git/trunk/.waf3-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 372, in runnable_status
> |     new_sig=self.signature()
> |   File "/home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/guitarix/0.40.0+gitAUTOINC+9e6dbe30cb-r0/git/trunk/.waf3-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 353, in signature
> |     self.sig_explicit_deps()
> |   File "/home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/guitarix/0.40.0+gitAUTOINC+9e6dbe30cb-r0/git/trunk/.waf3-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 428, in sig_explicit_deps
> |     upd(v)
> | TypeError: object supporting the buffer API required
> | 
> | WARNING: /home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/guitarix/0.40.0+gitAUTOINC+9e6dbe30cb-r0/temp/run.do_compile.8430:1 exit 1 from 'waf_do_compile'

I think upd() is called with None because when I modify as
[test.patch.txt](https://github.com/schnitzeltony/meta-musicians/files/4764738/test.patch.txt)

Build continues a tiny bit but fails later with:

> | DEBUG: Executing shell function do_compile
> | Waf: Entering directory `/home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/guitarix/0.40.0+gitAUTOINC+9e6dbe30cb-r0/build'
> | [161/289] Processing src/faust/drumseq.dsp
> | Waf: Leaving directory `/home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/guitarix/0.40.0+gitAUTOINC+9e6dbe30cb-r0/build'
> | Build failed
> | Traceback (most recent call last):
> |   File "/home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/guitarix/0.40.0+gitAUTOINC+9e6dbe30cb-r0/git/trunk/.waf3-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 180, in process
> |     ret=self.run()
> |   File "waftools/faust.py", line 18, in dsp2cc
> |     lst = [task.proc.abspath(), "-o", dst]
> | AttributeError: 'NoneType' object has no attribute 'abspath'

Any suggestions?

**Comment by brummer10** [comment]
> The referenced patch does not apply cleanly on 0.39.0 

That may be related to the diff in the Fix-LV2-types.patch (const struct _LV2UI_Descriptor) you use, maybe use this instead will lead to a clean apply: 
https://salsa.debian.org/multimedia-team/guitarix/-/blob/master/debian/patches/0002-Fix-LV2-types.patch

> Any suggestions?

I've seen similar errors which was related to anaconda been installed. 
Other than that, here is a tread about building guitarix 0.40.0 on a Pi 3B+, 
https://github.com/brummer10/guitarix/issues/8
It turns out that some small patches been needed to make it build and run successfully on a ARM device.

**Comment by schnitzeltony** [comment]
I re-read discussion on linuxmusicians [1] and the first result is: adding ` --no-faust` fixes compile.

[1] https://linuxmusicians.com/viewtopic.php?f=24&t=21562

**Comment by OE4AMW** [comment]
Hi,

thanks very much for the fast responses and the fix!
The recipe for 0.40.0 compiles and starts now without any errors.
